# docker run -p 80:80 nginx --> pull image from dockerhub and create container
kind: Pod
apiVersion: v1
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    name: catalogue
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: cart
  namespace: roboshop
  labels:
    name: cart
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - catalogue
        topologyKey: topology.kubernetes.io/zone
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
# ---
# kind: Pod
# apiVersion: v1
# metadata:
#   name: user
#   namespace: roboshop
#   labels:
#     name: user
# spec:
#   affinity:
#     podAntiAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchExpressions:
#           - key: name
#             operator: In
#             values:
#             - cart
#         topologyKey: topology.kubernetes.io/zone
#   containers:
#   - image: nginx
#     name: nginx
#     ports:
#     - containerPort: 80