apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    name: nginx-service
    environment: DEV
spec:
  type: NodePort
  selector:
  # you should provide pod labels here
    course: kubernetes
  ports:
  - name: http-port
    protocol: TCP
    # service port
    port: 80
    # pod port
    targetPort: 80