#vol-0517b1437e1a99a8a
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  #storageClassName: ""
  awsElasticBlockStore:
      volumeID: "vol-0517b1437e1a99a8a"
      fsType: ext4