apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-dynamic-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: io1
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: efs-static-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 30Gi
#   storageClassName: "ebs-dynamic-sc"