# docker run -p 80:80 nginx --> pull image from dockerhub and create container
kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: roboshop
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80