# docker run -p 80:80 nginx --> pull image from dockerhub and create container
kind: Pod
apiVersion: v1
metadata:
  name: stress
spec:
  containers:
  - image: techworldwithsiva/stress:v1
    name: stress
    command: ["sleep", "2000"]
    resources:
      # soft limit, when a container is created it will get these resources
      requests:
        # number of cores
        cpu: "0.2"
        #ram
        memory: "128Mi"
      # hard level,if your containers cross the requests, limits are the maximum resources
      limits:
        cpu: "0.3"
        memory: "156Mi"
