apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test
data:
  CART_HOST: cart
  USER_HOST: user
  MYSQL_HOST: mysql.joindevops.com
  MYSQL_SCHEMA: cities
---
kind: Pod
apiVersion: v1
metadata:
  name: env-pod
spec:
  containers:
  - image: nginx
    name: env-pod
    env:
    - name: CART_HOST
      valueFrom:
        configMapKeyRef:
          name: config-test
          key: CART_HOST